export const fr = {
  app: { title: 'DroneMed - Agent Rural', subtitle: 'Madagascar' },
  home: { title: 'Accueil', newOrder: 'Nouvelle Commande', tracking: 'Suivi Drone', incidents: 'Signaler Incident', sync: 'Synchronisation', pending: 'Commandes en attente', noPending: 'Aucune commande en attente' },
  order: { title: 'Nouvelle Commande', patientName: 'Nom du patient', age: 'Âge', sex: 'Sexe', male: 'Homme', female: 'Femme', contact: 'Contact', bloodGroup: 'Groupe sanguin', symptoms: 'Symptômes', products: 'Produits médicamenteux', urgency: 'Niveau d\'urgence', low: 'Faible', medium: 'Moyen', high: 'Élevé', critical: 'Critique', submit: 'Soumettre la commande', submitting: 'Envoi en cours...', success: 'Commande soumise avec succès !', error: 'Erreur lors de la soumission', center: 'Centre de santé', selectCenter: 'Sélectionner un centre' },
  tracking: { title: 'Suivi Drone', noActive: 'Aucun vol actif', drone: 'Drone', status: 'Statut', battery: 'Batterie', speed: 'Vitesse', altitude: 'Altitude', position: 'Position', eta: 'ETA', confirm: 'Confirmer livraison', qrCode: 'Scanner QR Code', code: 'Code de confirmation', deliveryCode: 'Code livraison', confirmDelivery: 'Confirmer', confirming: 'Confirmation...', success: 'Livraison confirmée !', errorCode: 'Code invalide' },
  incident: { title: 'Signaler Incident', type: "Type d'incident", types: { droneDown: 'Drone tombé', wrongDelivery: 'Mauvaise livraison', missingProducts: 'Produits manquants', patientRefused: 'Patient refusé', other: 'Autre' }, description: 'Description', submit: 'Signaler', success: 'Incident signalé', error: 'Erreur lors du signalement' },
  sync: { lastSync: 'Dernière synchro', syncNow: 'Synchroniser maintenant', syncing: 'Synchronisation...', success: 'Synchronisation réussie', ordersSent: 'Commandes envoyées', incidentsSent: 'Incidents envoyés', ordersReceived: 'Commandes reçues' },
  common: { loading: 'Chargement...', error: 'Erreur', retry: 'Réessayer', cancel: 'Annuler', save: 'Enregistrer', delete: 'Supprimer', back: 'Retour' },
};
