export const mg = {
  app: { title: 'DroneMed - Mpiasa Ambanivohitra', subtitle: 'Madagasikara' },
  home: { title: 'Fandraisana', newOrder: 'Baiko Vaovao', tracking: 'Araho ny Drone', incidents: 'Hitan\'olana', sync: 'Fampifanarahana', pending: 'Baiko miandry', noPending: 'Tsy misy baiko miandry' },
  order: { title: 'Baiko Vaovao', patientName: 'Anaran\'ny marary', age: 'Taona', sex: 'Lahy/Vavy', male: 'Lahy', female: 'Vavy', contact: 'Fifandraisana', bloodGroup: 'Karazana ra', symptoms: 'Soritr\'aretina', products: 'Fanafody ilaina', urgency: 'Haton\'ny maika', low: 'Ambany', medium: 'Antonontonony', high: 'Avo', critical: 'Maika be', submit: 'Alefaso ny baiko', submitting: 'Mandefa...', success: 'Voalefa soamantsara ny baiko !', error: 'Tsy nahalefa ny baiko', center: 'Toeram-pitsaboana', selectCenter: 'Fidio ny toeram-pitsaboana' },
  tracking: { title: 'Araho ny Drone', noActive: 'Tsy misy sidina mandeha', drone: 'Drone', status: 'Toerana', battery: 'Bateria', speed: 'Haingana', altitude: 'Haavo', position: 'Toerana', eta: 'Fotoana hahatongavana', confirm: 'Hamarino ny fanaterana', qrCode: 'Skanio ny QR Code', code: 'Kaody fanamarinana', deliveryCode: 'Kaody fanaterana', confirmDelivery: 'Hamarino', confirming: 'Manamarina...', success: 'Voamarina ny fanaterana !', errorCode: 'Kaody diso' },
  incident: { title: 'Hitan\'olana', type: 'Karazana olana', types: { droneDown: 'Nianjera ny drone', wrongDelivery: 'Diso fanaterana', missingProducts: 'Tsy ampy ny fanafody', patientRefused: 'Nandà ny marary', other: 'Hafa' }, description: 'Famaritana', submit: 'Alefaso', success: 'Voalefa ny olana', error: 'Tsy nahalefa ny olana' },
  sync: { lastSync: 'Fampifanarahana farany', syncNow: 'Fampifanarahana izao', syncing: 'Mampifanaraka...', success: 'Fampifanarahana vita', ordersSent: 'Baiko nalefa', incidentsSent: 'Olana nalefa', ordersReceived: 'Baiko voaray' },
  common: { loading: 'Mandrà...', error: 'Hadisoana', retry: 'Andramo indray', cancel: 'Ajanona', save: 'Tehirizo', delete: 'Fafao', back: 'Miverena' },
};
